### ISSUE TITLE
Website at blkidx.org doesn't exist

### ISSUE THREAD

**Issue by suriyaa** [vertcoin-project/blockchain-indexer#3]
Hello,

I clicked this link on https://github.com/vertcoin-project/blockchain-indexer:

![screenshot_2018-05-18 vertcoin-project blockchain-indexer](https://user-images.githubusercontent.com/5073946/40245627-8be54c64-5ac6-11e8-8171-0273d5e3cf69.png)

----

The Blockchain indexer website under the [blkidx.org](https://blkidx.org/) domain address doesn't exist.

It displays only an 404 error from a Nginx server (with the version 1.13.7):

![screenshot_2018-05-18 404 not found](https://user-images.githubusercontent.com/5073946/40245489-2972e604-5ac6-11e8-916b-4b06fbc6cd08.png)

----

--[**Suriyaa Sundararuban**](https://suriyaa.tk/) <a href="https://github.com/SuriyaaKudoIsc"><img src="https://assets-cdn.github.com/images/icons/emoji/octocat.png" alt="GitHub Developer" width="18" height="18" /></a> <a href="https://vertcoin.org/team/"><img src="https://cdn.discordapp.com/emojis/430323443918176256.png" alt="Future Official Vertcoin Developer?" width="20" height="20" /></a>

**Comment by suriyaa** [comment]
ping @gertjaap @metalicjames

**Comment by metalicjames** [comment]
The main-net index is at https://vtc.blkidx.org, testnet: https://tvtc.blkidx.org. E.g. https://vtc.blkidx.org/addressTxos/vtc1q3ejfy6732q373rlwc5d2pa2w0rzhd93wnhs23v

**Comment by suriyaa** [comment]
Can you please update this link:

![screenshot_2018-05-18 vertcoin-project blockchain-indexer](https://user-images.githubusercontent.com/5073946/40245627-8be54c64-5ac6-11e8-8171-0273d5e3cf69.png)

**Comment by gertjaap** [comment]
There's no website to this and redirecting its main domain to a specific API endpoint makes no sense. So i made the domain redirect to this github page in stead.

**Comment by suriyaa** [comment]
Ok.
